### ISSUE TITLE
I've updated to the last version, and the function "sniffing for changes" cannot find the users anymore

### ISSUE THREAD

**Issue by juliozamboom** [lgalete/sniff-detector#3]
![image](https://github.com/lgalete/sniff-detector/assets/128169023/53eefeb8-68ba-43f0-a7b1-fddebbc7b98d)

how can i fix it?

**Comment by lgalete** [comment]
@juliozamboom Should be fixed after febc079, can you check again?

**Comment by juliozamboom** [comment]
![image](https://github.com/lgalete/sniff-detector/assets/128169023/53c854b7-7942-48ea-9e33-1cbed29d084b)

still not working

**Comment by lgalete** [comment]
@juliozamboom No idea then, I'll take a better look later. In the meantime, feel free to open a PR
